import createFetchClient from 'openapi-fetch'
import createClient from 'openapi-react-query'
import { QueryClient } from '@tanstack/react-query'
import type { paths } from './v1' // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_BASEURL,
})

export const $api = createClient(fetchClient)
export const queryClient = new QueryClient()